# Generated by Django 5.1.5 on 2025-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBS', '0002_image_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%y')),
                ('site', models.URLField(default='')),
            ],
        ),
    ]
