# Generated by Django 5.1.5 on 2025-06-20 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBS', '0003_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
