# Generated by Django 5.1.5 on 2025-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBS', '0004_web_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='caption',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
