# Generated by Django 5.1.5 on 2025-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBS', '0005_web_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='site',
            field=models.URLField(max_length=300),
        ),
    ]
